<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;


class RouteTest extends TestCase
{
    use DatabaseMigrations;
    //use RefreshDatabase;

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function tearDown(): void
    {
        //Пришлось в тестах вручную дропать таблицу, т.к. SQLite не поддерживает дроп ключа и не может выполнить роллбэк миграции 2020_04_11_163705_alter_table_news_add_category. В конце тестов лезла следующая ошибка:
        //SQLite doesn't support dropping foreign keys (you would need to re-create the table).
        Schema::dropIfExists('news');

        parent::tearDown(); // TODO: Change the autogenerated stub

    }

    public function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    public function test()
    {
        $response = $this->get('/');
        $response->assertStatus(200);
        $response->assertSee('nav-link active');

        $response = $this->get('/admin');
        $response->assertStatus(200);
        $response->assertSeeText('Корень админки');
        $response->assertSee('nav-link active');

        $response = $this->get('/admin/downloadNewsByCategory');
        $response->assertStatus(200);

        $response = $this->get('/categories');
        $response->assertStatus(200);
        $response->assertSeeText('Категории');
        $response->assertSee('nav-link active');

        $response = $this->get('/news');
        $response->assertStatus(200);
        $response->assertSeeText('Все новости');
        $response->assertSee('nav-link active');

        $response = $this->get('http://laravel.local/news/1');
        $response->assertStatus(200);

        $response = $this->get('/admin/categories/create');
        $response->assertStatus(200);
        $response->assertSee('form');
        $response->assertSee('submit');

        $response = $this->get('/categories/sport');
        $response->assertStatus(200);
        $response->assertSeeText('Спорт');
    }
}
